interface PathD {
	[Internal="size"] int numPoints();
	[CObject,Internal="HLClip::PathD_getPoint"] void getPoint(int idx, double *coordinates2D);
	[CObject,Internal="HLClip::PathD_getPoints"] void getPoints( double *coordinates2D);
};

[Internal="PolyTreeD"]
interface PathTreeD {
	[Internal="Count"] int numChildren();
	[CObject,Internal="HLClip::PolyTreeD_getPath",Const] PathD getPath();
	[CObject,Internal="HLClip::PolyTreeD_getChild",Const] PathTreeD getChild(int idx);
	
};

interface PathsD {
	void PathsD();

	[CObject, Internal="HLClip::addPolygonD"] void addPolygonD( double * coordinates, int vertCount );
	[CObject, Internal="HLClip::addPolygonsD"] void addPolygonsD( double * coordinates, int *vertCount, int polyCount );
	[CObject, Internal="HLClip::unionAll"] PathsD unionAll(bool fillHoles);
	[CObject, Internal="HLClip::unionAllAsTree"] PathTreeD unionAllAsTree();
	[Internal="size"] int numPolygons();
	[CObject,Internal="HLClip::polygonCounts"] int polygonVertCounts( int *counts ); 
	[CObject,Internal="HLClip::getAllCoordinates"] void getAllCoordinates( double *coordinates2D ); 
};


[Internal="PartitionPolyIt"]
interface PartitionPolyIt {

	[Internal="GetNumPoints"] int getNumPoints();
	[Internal="GetPoints"] void getPoints(double *points);
	[Internal="IsValid"]  bool isValid();
	[Internal="Next"]  bool next();
};


[Internal="TPPLPolyList"] 
interface PartitionPolyList {
	void PartitionPolyList();
	[CObject, Internal="HLPartition::NumPolys"] int numPolys(  );
	[CObject, Internal="HLPartition::PolyList_AddPoly",Const] PartitionPoly addPoly( int pointCount, double *coordinates  );
	[CObject, Internal="HLPartition::GetPolyIt"] PartitionPolyIt getPolyIt();
	[CObject, Internal="HLPartition::PolyList_RemoveHoles"] bool removeHoles( PartitionPolyList result );
	[CObject, Internal="HLPartition::PolyList_ConvexPartition"] bool convexPartition( PartitionPolyList result );
};


[Internal="TPPLPoly"] 
interface PartitionPoly {
	void PartitionPoly();
	[ Internal="SetHole"] void setHole( bool hole);
	[ Internal="IsHole"] bool isHole( );

	[CObject, Internal="HLPartition::InitD"] void initD( double *coordinates, int vertCount);
	[CObject, Internal="HLPartition::ConvexPartitionOptimal"] void convexPartitionOptimal( PartitionPolyList result );
};


// need to add https://github.com/ivanfratric/polypartition

